# Generated by Django 4.2.11 on 2025-07-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_paid_order_stripe_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_session_id',
        ),
    ]
