# Generated by Django 4.2.11 on 2025-07-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_is_paid_order_payment_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
